# Generated by Django 3.0.6 on 2020-06-21 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('course', models.IntegerField(blank=True, choices=[(0, 'Administração'), (1, 'Ciência da Computação'), (2, 'Ciências Atmosféricas'), (3, 'Ciências Biológicas Licenciatura'), (4, 'Engenharia Ambiental'), (5, 'Engenharia Civil'), (6, 'Engenharia de Bioprocessos'), (7, 'Engenharia de Computação'), (8, 'Engenharia de Controle e Automação'), (9, 'Engenharia de Energia'), (10, 'Engenharia de Materiais'), (11, 'Engenharia de Produção'), (12, 'Engenharia Elétrica'), (13, 'Engenharia Eletrônica'), (14, 'Engenharia Hídrica'), (15, 'Engenharia Mecânica'), (16, 'Engenharia Mecânica Aeronáutica'), (17, 'Engenharia Química'), (18, 'Física Bacharelado'), (19, 'Física Licenciatura'), (20, 'Matemática Bacharelado'), (21, 'Matemática Licenciatura'), (22, 'Química Bacharelado'), (23, 'Química Licenciatura'), (24, 'Sistemas de Informação')], null=True)),
                ('user_permissions', models.IntegerField(choices=[(0, 'Aluno'), (1, 'Professor'), (2, 'Superaluno'), (3, 'Administrador')])),
                ('code', models.CharField(max_length=50, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
