# Generated by Django 2.2.3 on 2020-06-07 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenericMarker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.IntegerField(choices=[(0, 'Grupo de Estudos'), (1, 'Atividades Extras'), (3, 'Eventos'), (2, 'Salas e Locais')], default=0)),
                ('description', models.CharField(default='', max_length=300)),
                ('latitude', models.CharField(default='', max_length=100)),
                ('longitude', models.CharField(default='', max_length=100)),
            ],
            options={
                'ordering': ('type',),
            },
        ),
        migrations.CreateModel(
            name='ConstructionMarker',
            fields=[
                ('genericmarker_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='markers.GenericMarker')),
                ('construction_type', models.IntegerField(choices=[(0, 'Em Sala'), (1, 'Em Corredor'), (3, 'Em Bloco'), (4, 'Em Rua'), (4, 'Em Predio'), (5, 'Em Banheiro')])),
            ],
            options={
                'ordering': ('construction_type',),
            },
            bases=('markers.genericmarker',),
        ),
        migrations.CreateModel(
            name='EventMarker',
            fields=[
                ('genericmarker_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='markers.GenericMarker')),
                ('event_type', models.IntegerField(choices=[(0, 'Workshop'), (1, 'Cursos'), (3, 'Seminário'), (4, 'Encontro'), (5, 'Semana'), (6, 'Simpósio'), (7, 'Jornada'), (8, 'Mesa-redonda'), (9, 'Conferência'), (10, 'Congresso'), (11, 'Painel'), (12, 'Fórum'), (13, 'Colóquio')])),
                ('event_date', models.DateTimeField()),
            ],
            options={
                'ordering': ('event_type',),
            },
            bases=('markers.genericmarker',),
        ),
        migrations.CreateModel(
            name='ExtraActivityMarker',
            fields=[
                ('genericmarker_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='markers.GenericMarker')),
                ('activity_type', models.CharField(default='', max_length=300)),
            ],
            options={
                'ordering': ('activity_type',),
            },
            bases=('markers.genericmarker',),
        ),
        migrations.CreateModel(
            name='StudyGroupMarker',
            fields=[
                ('genericmarker_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='markers.GenericMarker')),
                ('group_size', models.PositiveIntegerField()),
                ('discipline', models.CharField(default='', max_length=300)),
                ('class_group', models.CharField(default='', max_length=300)),
            ],
            options={
                'ordering': ('group_size',),
            },
            bases=('markers.genericmarker',),
        ),
    ]
