# Generated by Django 3.0.6 on 2020-10-13 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.IntegerField(choices=[(0, 'Grupo de Estudos'), (1, 'Atividades Extras'), (2, 'Eventos'), (3, 'Salas e Locais'), (4, 'Obras')], default=0)),
                ('description', models.CharField(default='', max_length=300)),
                ('latitude', models.CharField(default='', max_length=100)),
                ('longitude', models.CharField(default='', max_length=100)),
            ],
            options={
                'ordering': ('type',),
            },
        ),
        migrations.CreateModel(
            name='StudyGroupMarker',
            fields=[
                ('marker_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='markers.Marker')),
                ('group_size', models.PositiveIntegerField()),
                ('discipline', models.CharField(default='', max_length=300)),
                ('class_group', models.CharField(default='', max_length=300)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.Profile')),
            ],
            options={
                'ordering': ('group_size',),
            },
            bases=('markers.marker',),
        ),
        migrations.CreateModel(
            name='GenericMarker',
            fields=[
                ('marker_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='markers.Marker')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.Profile')),
            ],
            options={
                'ordering': ('type',),
            },
            bases=('markers.marker',),
        ),
        migrations.CreateModel(
            name='ExtraActivityMarker',
            fields=[
                ('marker_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='markers.Marker')),
                ('activity_type', models.CharField(default='', max_length=300)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.Profile')),
            ],
            options={
                'ordering': ('activity_type',),
            },
            bases=('markers.marker',),
        ),
        migrations.CreateModel(
            name='EventMarker',
            fields=[
                ('marker_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='markers.Marker')),
                ('event_type', models.IntegerField(choices=[(0, 'Workshop'), (1, 'Cursos'), (2, 'Seminário'), (3, 'Encontro'), (4, 'Semana'), (5, 'Simpósio'), (6, 'Jornada'), (7, 'Mesa-redonda'), (8, 'Conferência'), (9, 'Congresso'), (10, 'Painel'), (11, 'Fórum'), (12, 'Colóquio')])),
                ('event_date', models.DateTimeField()),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.Profile')),
            ],
            options={
                'ordering': ('event_type',),
            },
            bases=('markers.marker',),
        ),
        migrations.CreateModel(
            name='ConstructionMarker',
            fields=[
                ('marker_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='markers.Marker')),
                ('construction_type', models.IntegerField(choices=[(0, 'Em Sala'), (1, 'Em Corredor'), (2, 'Em Bloco'), (3, 'Em Rua'), (4, 'Em Predio'), (5, 'Em Banheiro')])),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.Profile')),
            ],
            options={
                'ordering': ('construction_type',),
            },
            bases=('markers.marker',),
        ),
    ]
