# Generated by Django 2.2.3 on 2020-06-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericmarker',
            name='type',
            field=models.IntegerField(choices=[(0, 'Grupo de Estudos'), (1, 'Atividades Extras'), (2, 'Eventos'), (3, 'Salas e Locais'), (4, 'Obras')], default=0),
        ),
    ]
