# Generated by Django 2.2.3 on 2020-06-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0002_auto_20200607_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionmarker',
            name='construction_type',
            field=models.IntegerField(choices=[(0, 'Em Sala'), (1, 'Em Corredor'), (2, 'Em Bloco'), (3, 'Em Rua'), (4, 'Em Predio'), (5, 'Em Banheiro')]),
        ),
        migrations.AlterField(
            model_name='eventmarker',
            name='event_type',
            field=models.IntegerField(choices=[(0, 'Workshop'), (1, 'Cursos'), (2, 'Seminário'), (3, 'Encontro'), (4, 'Semana'), (5, 'Simpósio'), (6, 'Jornada'), (7, 'Mesa-redonda'), (8, 'Conferência'), (9, 'Congresso'), (10, 'Painel'), (11, 'Fórum'), (12, 'Colóquio')]),
        ),
    ]
