# Generated by Django 3.0.6 on 2020-11-22 05:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.Profile'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='content',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
